node('host') {
    stage('Cleaning workspace') {
        deleteDir()
    }
    stage('Download from git') {
        git 'https://github.com/spring-guides/gs-spring-boot.git'
    }
    stage('Trying to build') {
        docker.image('gradle').inside {
            sh 'gradle -b initial/build.gradle build'
        }
    }
    stage('Prepare environment to run app') {
        sh 'mkdir spring'
        sh 'wget -N https://raw.githubusercontent.com/VadzimTarasiuk/docker/vadzim_tarasiuk_day2/docker-2/resources/spring/docker-compose.yml'
        sh 'wget -N -P spring/ https://raw.githubusercontent.com/VadzimTarasiuk/docker/vadzim_tarasiuk_day2/docker-2/resources/spring/spring.Dockerfile'
    }
    stage('Run application') {
        sh 'docker-compose up -d' 
    }
    stage('Check app running') {
        sh 'sleep 5'
        sh 'curl http://127.0.0.1:8081' 
    }
    stage('Clean up') {
        sh 'docker-compose stop && docker-compose rm -f'
    }
}
